### post coal
POST http://localhost:3001/api/coal

### find all coals
GET http://localhost:3001/api/feed

### find by authorId
GET http://localhost:3001/api/coal/4

### find by user id
GET http://localhost:3001/api/user/4

### find all users
GET http://localhost:3001/api/users
